# Generated by Django 5.2.2 on 2025-06-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_author_customer_genre_publisher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="price",
            field=models.FloatField(verbose_name="Цена доставки"),
        ),
    ]
